USE Lab3;   

CREATE TABLE gym (
    address VARCHAR(100) PRIMARY KEY NOT NULL,
    nameofgym VARCHAR(100) NOT NULL
    
);

INSERT INTO gym(address, nameofgym)
values 
insert into gym (name, weight, condition, quantity) values ('Bigtax', 18, 'Mrs', 19);
insert into gym (name, weight, condition, quantity) values ('Y-Solowarm', 18, 'Mr', 52);
insert into gym (name, weight, condition, quantity) values ('Rank', 32, 'Mrs', 38);
insert into gym (name, weight, condition, quantity) values ('Ventosanzap', 62, 'Rev', 29);
insert into gym (name, weight, condition, quantity) values ('Greenlam', 57, 'Ms', 81);
insert into gym (name, weight, condition, quantity) values ('Cookley', 5, 'Honorable', 39);
insert into gym (name, weight, condition, quantity) values ('Asoka', 3, 'Rev', 86);
insert into gym (name, weight, condition, quantity) values ('Pannier', 18, 'Mrs', 40);
insert into gym (name, weight, condition, quantity) values ('Kanlam', 68, 'Rev', 75);
insert into gym (name, weight, condition, quantity) values ('Ronstring', 53, 'Mrs', 4);
insert into gym (name, weight, condition, quantity) values ('Quo Lux', 83, 'Dr', 69);
insert into gym (name, weight, condition, quantity) values ('Andalax', 22, 'Mr', 20);
insert into gym (name, weight, condition, quantity) values ('Trippledex', 31, 'Honorable', 34);
insert into gym (name, weight, condition, quantity) values ('Wrapsafe', 54, 'Mrs', 66);
insert into gym (name, weight, condition, quantity) values ('Konklux', 65, 'Ms', 14);
insert into gym (name, weight, condition, quantity) values ('Treeflex', 80, 'Mrs', 96);
insert into gym (name, weight, condition, quantity) values ('Keylex', 50, 'Dr', 27);
insert into gym (name, weight, condition, quantity) values ('Job', 45, 'Mr', 100);
insert into gym (name, weight, condition, quantity) values ('Opela', 44, 'Dr', 31);
insert into gym (name, weight, condition, quantity) values ('Lotstring', 2, 'Honorable', 99);
insert into gym (name, weight, condition, quantity) values ('Andalax', 65, 'Mrs', 72);
insert into gym (name, weight, condition, quantity) values ('Fix San', 31, 'Honorable', 76);
insert into gym (name, weight, condition, quantity) values ('Veribet', 3, 'Mr', 1);
insert into gym (name, weight, condition, quantity) values ('Lotstring', 76, 'Ms', 76);
insert into gym (name, weight, condition, quantity) values ('Transcof', 65, 'Mrs', 62);
insert into gym (name, weight, condition, quantity) values ('Gembucket', 57, 'Ms', 49);
insert into gym (name, weight, condition, quantity) values ('Bitchip', 50, 'Honorable', 20);
insert into gym (name, weight, condition, quantity) values ('Fix San', 94, 'Mr', 67);
insert into gym (name, weight, condition, quantity) values ('Ronstring', 73, 'Rev', 96);
insert into gym (name, weight, condition, quantity) values ('Flowdesk', 45, 'Ms', 26);
insert into gym (name, weight, condition, quantity) values ('Span', 64, 'Mrs', 90);
insert into gym (name, weight, condition, quantity) values ('Tres-Zap', 95, 'Mrs', 68);
insert into gym (name, weight, condition, quantity) values ('Greenlam', 15, 'Honorable', 4);
insert into gym (name, weight, condition, quantity) values ('Cardify', 9, 'Mr', 12);
insert into gym (name, weight, condition, quantity) values ('Bitwolf', 53, 'Mrs', 41);
insert into gym (name, weight, condition, quantity) values ('Prodder', 5, 'Rev', 11);
insert into gym (name, weight, condition, quantity) values ('Zontrax', 97, 'Dr', 57);
insert into gym (name, weight, condition, quantity) values ('Tin', 21, 'Honorable', 14);
insert into gym (name, weight, condition, quantity) values ('Kanlam', 76, 'Dr', 76);
insert into gym (name, weight, condition, quantity) values ('Transcof', 76, 'Mr', 72);
insert into gym (name, weight, condition, quantity) values ('Gembucket', 30, 'Honorable', 67);
insert into gym (name, weight, condition, quantity) values ('Keylex', 95, 'Dr', 30);
insert into gym (name, weight, condition, quantity) values ('Aerified', 30, 'Mr', 22);
insert into gym (name, weight, condition, quantity) values ('Subin', 23, 'Mrs', 53);
insert into gym (name, weight, condition, quantity) values ('Bamity', 94, 'Honorable', 79);
insert into gym (name, weight, condition, quantity) values ('Flexidy', 33, 'Honorable', 75);
insert into gym (name, weight, condition, quantity) values ('Flowdesk', 42, 'Ms', 77);
insert into gym (name, weight, condition, quantity) values ('Asoka', 33, 'Honorable', 48);
insert into gym (name, weight, condition, quantity) values ('Regrant', 100, 'Mr', 43);
insert into gym (name, weight, condition, quantity) values ('Redhold', 13, 'Dr', 22);
insert into gym (name, weight, condition, quantity) values ('Duobam', 90, 'Honorable', 92);
insert into gym (name, weight, condition, quantity) values ('Pannier', 84, 'Dr', 89);
insert into gym (name, weight, condition, quantity) values ('Flexidy', 72, 'Honorable', 2);
insert into gym (name, weight, condition, quantity) values ('Alphazap', 23, 'Dr', 26);
insert into gym (name, weight, condition, quantity) values ('Y-Solowarm', 80, 'Mr', 25);
insert into gym (name, weight, condition, quantity) values ('Asoka', 62, 'Honorable', 20);
insert into gym (name, weight, condition, quantity) values ('Viva', 15, 'Dr', 4);
insert into gym (name, weight, condition, quantity) values ('Hatity', 41, 'Rev', 36);
insert into gym (name, weight, condition, quantity) values ('Bitwolf', 27, 'Ms', 38);
insert into gym (name, weight, condition, quantity) values ('Span', 3, 'Ms', 11);
insert into gym (name, weight, condition, quantity) values ('Zaam-Dox', 46, 'Mrs', 53);
insert into gym (name, weight, condition, quantity) values ('Mat Lam Tam', 14, 'Honorable', 10);
insert into gym (name, weight, condition, quantity) values ('Holdlamis', 100, 'Honorable', 66);
insert into gym (name, weight, condition, quantity) values ('Regrant', 48, 'Rev', 22);
insert into gym (name, weight, condition, quantity) values ('Daltfresh', 39, 'Honorable', 28);
insert into gym (name, weight, condition, quantity) values ('Stronghold', 58, 'Mrs', 53);
insert into gym (name, weight, condition, quantity) values ('Alpha', 31, 'Honorable', 51);
insert into gym (name, weight, condition, quantity) values ('Overhold', 88, 'Ms', 100);
insert into gym (name, weight, condition, quantity) values ('Lotlux', 32, 'Honorable', 69);
insert into gym (name, weight, condition, quantity) values ('Sub-Ex', 32, 'Rev', 53);
insert into gym (name, weight, condition, quantity) values ('Zontrax', 48, 'Mr', 37);
insert into gym (name, weight, condition, quantity) values ('Opela', 94, 'Dr', 55);
insert into gym (name, weight, condition, quantity) values ('Zamit', 59, 'Mr', 55);
insert into gym (name, weight, condition, quantity) values ('Bitchip', 54, 'Mrs', 6);
insert into gym (name, weight, condition, quantity) values ('Biodex', 93, 'Dr', 33);
insert into gym (name, weight, condition, quantity) values ('Voltsillam', 88, 'Honorable', 70);
insert into gym (name, weight, condition, quantity) values ('Aerified', 72, 'Dr', 50);
insert into gym (name, weight, condition, quantity) values ('Temp', 38, 'Mrs', 14);
insert into gym (name, weight, condition, quantity) values ('Treeflex', 57, 'Honorable', 38);
insert into gym (name, weight, condition, quantity) values ('Transcof', 13, 'Dr', 72);
insert into gym (name, weight, condition, quantity) values ('Zathin', 86, 'Mr', 92);
insert into gym (name, weight, condition, quantity) values ('Holdlamis', 14, 'Mr', 6);
insert into gym (name, weight, condition, quantity) values ('Stringtough', 2, 'Dr', 51);
insert into gym (name, weight, condition, quantity) values ('Tin', 84, 'Mr', 7);
insert into gym (name, weight, condition, quantity) values ('Tempsoft', 17, 'Rev', 86);
insert into gym (name, weight, condition, quantity) values ('Stringtough', 25, 'Mr', 64);
insert into gym (name, weight, condition, quantity) values ('Otcom', 55, 'Rev', 31);
insert into gym (name, weight, condition, quantity) values ('Flowdesk', 13, 'Ms', 3);
insert into gym (name, weight, condition, quantity) values ('Fix San', 30, 'Rev', 47);
insert into gym (name, weight, condition, quantity) values ('Y-find', 82, 'Ms', 29);
insert into gym (name, weight, condition, quantity) values ('Bitwolf', 95, 'Honorable', 9);
insert into gym (name, weight, condition, quantity) values ('Tres-Zap', 71, 'Rev', 76);
insert into gym (name, weight, condition, quantity) values ('Cookley', 23, 'Ms', 35);
insert into gym (name, weight, condition, quantity) values ('Voyatouch', 40, 'Rev', 71);
insert into gym (name, weight, condition, quantity) values ('Tresom', 59, 'Dr', 79);
insert into gym (name, weight, condition, quantity) values ('Ventosanzap', 27, 'Mrs', 19);
insert into gym (name, weight, condition, quantity) values ('Y-find', 74, 'Rev', 81);
insert into gym (name, weight, condition, quantity) values ('Stim', 41, 'Mr', 64);
insert into gym (name, weight, condition, quantity) values ('Zamit', 30, 'Mr', 71);
insert into gym (name, weight, condition, quantity) values ('Zontrax', 74, 'Mrs', 30);