/* Script to set up gym entity. Copy paste in terminal 
after running first script in setup.sql file  */

USE Lab3;   

CREATE TABLE gym (
    address VARCHAR(100) PRIMARY KEY NOT NULL,
    nameofgym VARCHAR(100) NOT NULL
    
);

INSERT INTO gym(address, nameofgym)
values 
 ('Jacobi-Gleason', '8357 Scoville Center'),
 ('Gerhold and Sons', '3555 Elmside Trail'),
 ('Roberts, Osinski and Swaniawski', '4423 Mcbride Street'),
 ('Gottlieb-Runte', '5175 Moulton Street'),
 ('Barrows and Sons', '559 Luster Crossing'),
 ('Rutherford, Herman and McLaughlin', '804 Portage Plaza'),
 ('Ward-Runte', '801 Porter Terrace'),
 ('O''Reilly, O''Keefe and Reilly', '0140 Oriole Drive'),
 ('Lynch and Sons', '7443 Bayside Park'),
 ('Rohan-Cole', '9 Hoffman Way'),
 ('Emmerich-Hansen', '6 Hollow Ridge Point'),
 ('Bergnaum-Swift', '6699 Dawn Crossing'),
 ('Hettinger-Batz', '89 Gina Park'),
 ('Bode Inc', '69 Stuart Terrace'),
 ('Dickens-Schimmel', '5 Dryden Terrace'),
 ('O''Conner-Harvey', '5 Forster Hill'),
 ('Hermann Inc', '76053 Ridge Oak Court'),
 ('Kihn Inc', '33534 Warrior Park'),
 ('Zemlak, Lehner and Blanda', '68162 Anniversary Park'),
 ('Kemmer, Beatty and Ondricka', '35535 Blaine Place'),
 ('Zboncak-Gislason', '7148 Pleasure Junction'),
 ('Hudson, Tillman and Mayer', '1945 Southridge Street'),
 ('Olson-Frami', '35 Colorado Park'),
 ('Raynor-Streich', '05 Schlimgen Junction'),
 ('Zboncak and Sons', '56 Petterle Trail'),
 ('Durgan Group', '644 Logan Pass'),
 ('Weber, Heaney and Cremin', '7013 Summer Ridge Trail'),
 ('Kassulke, Altenwerth and Farrell', '217 Bay Alley'),
 ('Turner Group', '4 Esker Crossing'),
 ('Murazik, Brakus and Murray', '668 Waywood Parkway'),
 ('Bernhard-Collier', '1864 Bellgrove Junction'),
 ('Boyer, Beahan and Spinka', '15 Mitchell Crossing'),
 ('Kuhic, Watsica and Farrell', '5 Cherokee Lane'),
 ('Howe Inc', '3865 Atwood Pass'),
 ('McDermott LLC', '23690 Cambridge Terrace'),
 ('Ritchie-Streich', '228 Dapin Lane'),
 ('Kirlin-Larson', '36463 Moose Avenue'),
 ('Strosin, Kunde and Farrell', '3 Nova Hill'),
 ('Gislason Inc', '16 Pennsylvania Junction'),
 ('Herzog and Sons', '77 Charing Cross Drive'),
 ('Lindgren-Kuhlman', '4 Bartillon Avenue'),
 ('Yundt-Jacobi', '12 Rigney Drive'),
 ('Kohler Group', '5041 Carpenter Crossing'),
 ('Stamm-Weimann', '7 Morningstar Junction'),
 ('Okuneva, Jaskolski and Rogahn', '18257 Muir Street'),
 ('Spencer, Auer and McDermott', '4 Bunting Circle'),
 ('Nitzsche, Cartwright and Streich', '26 Scott Court'),
 ('Kautzer Group', '44460 Mayer Avenue'),
 ('Reynolds-VonRueden', '298 Forest Center'),
 ('MacGyver, Romaguera and Kirlin', '6 Hintze Alley'),
 ('Yundt, Lesch and Bogisich', '2730 Everett Hill'),
 ('Hahn-Smith', '87127 Westport Way'),
 ('Satterfield-D''Amore', '57 Pearson Plaza'),
 ('Kub-Fahey', '2885 Southridge Hill'),
 ('Crona and Sons', '80029 Green Alley'),
 ('Brekke-Stamm', '9096 John Wall Lane'),
 ('Stoltenberg, Huels and Hilpert', '5036 Stoughton Junction'),
 ('Johns Group', '95026 Lakewood Gardens Park'),
 ('Murray, Bernier and Bartoletti', '31429 Jay Terrace'),
 ('Krajcik-Feil', '832 Lotheville Avenue'),
 ('Green and Sons', '9039 International Avenue'),
 ('Gottlieb, Abernathy and Bauch', '15842 Rutledge Court'),
 ('Morar, Brakus and Greenfelder', '269 Graedel Pass'),
 ('Raynor and Sons', '16 Declaration Parkway'),
 ('Dach Group', '0917 Sunnyside Road'),
 ('Abshire Group', '60162 Toban Road'),
 ('Lemke LLC', '1 Ridge Oak Circle'),
 ('Kuhn-Hessel', '14 Oak Valley Alley'),
 ('Halvorson-Kunze', '687 Sullivan Plaza'),
 ('Purdy LLC', '28886 Sycamore Hill'),
 ('Kulas-Jones', '531 Bonner Park'),
 ('Kshlerin-Corkery', '07 Dovetail Hill'),
 ('Kreiger Inc', '38 Waubesa Court'),
 ('Goldner-Jacobs', '78 Nelson Road'),
 ('Boyer Inc', '60018 Dahle Parkway'),
 ('Hayes-Ruecker', '6157 Tomscot Way'),
 ('Kuhn, Mosciski and Lesch', '24 Morningstar Park'),
 ('Ebert and Sons', '905 Sunnyside Place'),
 ('Morar and Sons', '27641 Calypso Terrace'),
 ('Kuhic-Johnston', '48 Dovetail Trail'),
 ('Langosh Inc', '13134 Linden Circle'),
 ('Larson, Hauck and Koepp', '9445 Hollow Ridge Road'),
 ('Leffler LLC', '9908 Independence Trail'),
 ('Langworth-Koss', '6796 Mayfield Avenue'),
 ('Stroman and Sons', '21 Bayside Parkway'),
 ('Reilly-Jakubowski', '22 Golf Parkway'),
 ('Gutmann-Brakus', '32 Autumn Leaf Street'),
 ('Satterfield, Macejkovic and Hickle', '44 Welch Trail'),
 ('Kessler-Rodriguez', '65 Warrior Drive'),
 ('Jacobs-Skiles', '40 Melby Way'),
 ('Klein, Ferry and Prohaska', '1 7th Lane'),
 ('Smith and Sons', '77 Cherokee Alley'),
 ('Feil Group', '055 Dwight Hill'),
 ('Cummings-Waelchi', '7030 Fuller Junction'),
 ('Schmitt LLC', '19438 Heffernan Plaza'),
 ('Satterfield and Sons', '133 Morning Lane'),
 ('Langosh-Leuschke', '5 Melvin Alley'),
 ('Sauer Group', '17 Butternut Pass'),
 ('Rolfson-Barton', '457 Fuller Alley'),
 ('Dare-Purdy', '132 American Ash Court');
